### ISSUE TITLE
Retaining the form input even after submitting the form. 

### ISSUE THREAD

**Issue by sadhakbj** [aishek/jquery-keepFormData#4]
I am trying to implement your library. I followed your documentation. In my case I don't want my form to be reset after i submit the button. Is there any solution.

**Comment by anystar** [comment]
[snip]

The ability has already been implemented 

class="keepFormData" data-keep-form-data-clear-on-submit="no"

**Comment by sadhakbj** [comment]
Thank you. I will give a check once.
